services:
  - type: web
    name: weather-predictionmodel
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist/weather-project/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html